# name: Ð¡Ð±Ð¾Ñ€ÐºÐ° Ð¿Ñ€Ð¾ÐµÐºÑ‚Ð° Ð² production Ð¸ ÐµÐ³Ð¾ Ð¿ÑƒÐ±Ð»Ð¸ÐºÐ°Ñ†Ð¸Ñ Ð½Ð° GitHub Pages

# on:
#   push:
#     branches: ['main']
#   pull_request:
#     branches: ['main']

# env:
#   CI: false

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}

#     permissions:
#       contents: 'read'
#       id-token: 'write'
#       pages: 'write'
#       actions: 'write'
#       checks: 'write'
#       deployments: 'write'

#     strategy:
#       matrix:
#         node-version: [18.x]

#     steps:
#       - name: Checkout ðŸ‘€
#         uses: actions/checkout@v3

#       - name: Use Node.js ${{ matrix.node-version }} ðŸ‘€
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: 'npm'

#       - name: Install dependencies ðŸ’…
#         run: |
#           npm ci
#           npm audit fix

#       - name: Build the app ðŸ˜¤
#         run: npm run build

#       - name: Configure Git ðŸ¤¢
#         run: |
#           git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
#           git config --global user.name "${{ secrets.GIT_USER_NAME }}"
#           git config --global credential.helper "store --file=~/.git-credentials"
#           echo "https://${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

#       - name: Deploy to GitHub Pages ðŸ˜Ž
#         run: |
#           npx gh-pages -d dist -r https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Nico-kun123/Portfolio.git
